vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - shd101wyy.markdown-preview-enhanced
    - vortizhe.simple-ruby-erb
    - CraigMaslowski.erb
    - Vense.rails-snippets
    - wingrunr21.vscode-ruby